export const ACTIONS = {
    INIT: 'INIT',
    SELECT_POST: 'SELECT_POST',
    // EDIT_POST: 'EDIT_POST',
    // CREATE_POST: 'CREATE_POST',
    DELETE_POST: 'DELETE_POST',
    LIKE_DISLIKE_POST: 'LIKE_DISLIKE_POST',
}